spring.application.name=Finanace
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/Finance
spring.datasource.username=postgres
spring.datasource.password=helloworld!

spring.security.debug=true

# ? Enable DEBUG logs for authentication and authorization
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.authorization=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ? Enable DEBUG for JWT parsing (jjwt library)
logging.level.io.jsonwebtoken=DEBUG

# JPA settings (optional but useful)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=helloworld!

app.jwt.secret=3sK9dL8qW2xVnP4rT7yZbQ1mC6fHjUeA0GkR5tYpL8s=
app.jwt.expiration-ms=86400000

spring.session.store-type=none

